spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:database
    username: sa
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

public:
  api:
    base_url: "http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService"
    key: DmzirBx1o3IFtRJG7rt3GDH4V1gvPEG3OZPhL0bmVfGKcN9l9XNGnZFMG/CgZztpMJ75UfC/S4NhTBziaMREnA==
